image: atlas/rucio-clients

before_script:
  - yum update
  - yum install -y sshpass
  - yum install -y git

stages:
  - report
  - git

grid:
  stage: report
  script:
    - python3 gridspace.py --rse $DISK
  parallel:
    matrix:
      - DISK: [CERN-PROD_PHYS-EXOTICS, TOKYO-LCG2_PHYS-EXOTICS]
  artifacts:
    paths:
      - ./reports/$DISK.csv
    expire_in: 24h

eos:
  stage: report
  script:
    - python3 eos.py -s $SUBGROUP
  parallel:
    matrix:
      - SUBGROUP: [cdm, hqt, jdm, lpx, ueh]
  artifacts:
    paths:
      - ./reports/$SUBGROUP.csv
    expire_in: 24h

git:
  stage: git
  script:
    - git config user.email "exotics.diskspace.watcher@cern.ch"
    - git config user.name "ExoticsDiskspaceWatcher"
    - git remote add gitlab_origin https://oauth2:$ACCESS_TOKEN@gitlab.cern.ch/vaustrup/exoticsdiskspaceusage.git
    - git add reports/*.csv
    # commit and push only if changes present
    # https://stackoverflow.com/questions/22040113/how-to-let-jenkins-git-commit-only-if-there-are-changes
    - git diff --staged --quiet || (git commit -m "update subgroup data" && git push -o ci.skip gitlab_origin HEAD:main)
